import type { NextPage } from 'next';
import Head from 'next/head';
import { HomeLayout } from '../components/layouts/Home';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>JustChat - talk with everyone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HomeLayout />
    </div>
  )
}

export default Home
